version: "3.8"

services:
  backend:
    build: ./Backend
    ports:
      - "3001:3001"
    env_file:
      - ./Backend/.env
    networks:
      - app-network

  client:
    build: ./Client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
